id = "noir-and-blanc-theme"
name = "Noir & Blanc"
version = "0.1.1"
schema_version = 1
authors = ["Chase Weaver <chase.weaver34@gmail.com>"]
description = "Minimal black and white themes for Zed"
repository = "https://github.com/chaseweaver/noir-and-blanc"
